// Ficha técnica oficial (catálogo Colchões Franquia Ortobom). Só dados confirmados no catálogo.
const S5 = ["88 x 188","108 x 198","138 x 188","158 x 198","193 x 203"];
const SPECS = {
 "orion":{altura:"35 cm",medidas:["138 x 188","158 x 198","193 x 203"],garantia:["Molas: 5 anos","Espuma: 3 anos"],destaques:["Molas ensacadas individualmente","Lâmina de espuma HR Gel certificada, que atua como regulador térmico","Tecido em malha de alta gramatura com tecnologia V-Protect","Reforço lateral em poliuretano"]},
 "bellona":{altura:"31 cm",medidas:["138 x 188","158 x 198","193 x 203"],garantia:["Molas: 5 anos","Espuma: 3 anos"],destaques:["Pillow top com espuma viscoelástica certificada","Malha belga com tecnologia antiviral V-Protect","Molas Superpocket ensacadas individualmente","Faixa lateral em linho"]},
 "orthopur":{altura:"31 cm",medidas:S5,garantia:["Molas: 5 anos","Espuma: 3 anos"],destaques:["Tecnologia Fresh Touch, que ajuda a regular a temperatura durante a noite","Camada de conforto em espuma viscoelástica certificada","Malha Soft Stretch com micro furos para passagem de ar","Sistema No Turn"]},
 "liberty":{altura:"31 cm",medidas:S5,garantia:["Molas: 5 anos","Espuma: 3 anos"],destaques:["Malha belga com fios sustentáveis feitos de garrafas PET","Lâmina de espuma HR certificada","Molas Superpocket ensacadas individualmente","Sistema No Turn"]},
 "pro-forca":{altura:"31 cm",medidas:S5,garantia:["Espuma: 3 anos"],destaques:["Lâmina de espuma HR e lâmina extra firme certificadas","Lâmina de espuma sustentável certificada","Tecido antiderrapante","Sistema No Turn"]},
 "absolut-hybrid":{altura:"31 cm",medidas:S5,garantia:["Molas: 5 anos","Espuma: 3 anos"],destaques:["Sistema Hybrid dupla face: um lado mais firme e outro mais macio","Camada de conforto em espuma viscoelástica certificada","Molas Nanolastic bicônicas com resistência progressiva","Lâmina de espuma extra firme certificada"]},
 "ouro-spring":{altura:"31 cm",medidas:S5,garantia:["Molas: 5 anos","Espuma: 3 anos"],destaques:["Estrutura de molas de fio contínuo","Reforço lateral em poliuretano em todo o perímetro","Malha de poliéster que não retém calor","Sistema No Turn"]},
 "ortopedico-premium":{altura:"31 cm",medidas:["88 x 188","138 x 188","158 x 198"],garantia:["Espuma: 3 anos","Chapa: 1 ano"],destaques:["Chapa de madeira de reflorestamento tratada","Lâmina de espuma ultra firme certificada","Tecido em malha de poliéster e ecobambu","Sistema No Turn"]},
 "only":{altura:"25 cm",medidas:["138 x 188","158 x 198","193 x 203"],garantia:["Espuma: 10 anos"],destaques:["Embalado a vácuo: cabe em elevador e carro comum","Tecnologia V-Protect antiviral e antibacteriana","Lâmina de espuma Ultragel","Espuma HR (alta resiliência)"]},
 "pic-go":{altura:"17 cm",medidas:["88 x 188","138 x 188","158 x 198","193 x 203"],garantia:["Espuma: 1 ano"],destaques:["Embalado a vácuo, reduz em até 80% o volume","Capa removível com zíper","Lâmina de espuma Ultragel","Espuma extra firme certificada"]},
 "pro-saude-visco-adapt":{altura:"15 cm",medidas:["79 x 198","89 x 198","96 x 203","139 x 198","159 x 198"],garantia:["Espuma: 3 anos"],destaques:["Lâmina de espuma viscoelástica certificada","Lâmina de espuma HR certificada","Tecido antiderrapante","Sistema No Turn"]},
 "pro-saude-superpocket":{altura:"25 cm",medidas:S5,garantia:["Molas: 3 anos","Espuma: 2 anos"],destaques:["Molas Superpocket ensacadas individualmente","Lâmina de espuma firme certificada","Reforço lateral em poliuretano","Sistema No Turn"]},
 "pro-saude-nanolastic":{altura:"25 cm",medidas:S5,garantia:["Molas: 3 anos","Espuma: 2 anos"],destaques:["Molas Nanolastic bicônicas com resistência progressiva ao peso","Lâmina de espuma firme certificada","Reforço lateral em poliuretano","Sistema No Turn"]},
 "pro-saude-extra-firme":{altura:"25 cm",medidas:S5,garantia:["Espuma: 2 anos"],destaques:["Lâmina de espuma extra firme certificada","Tecido em malha de poliéster e viscose","Bordado em matelassê com espuma selada"]},
 "pro-saude-ortopedico":{altura:"25 cm",medidas:["88 x 188","108 x 198","138 x 188","158 x 198"],garantia:["Espuma: 2 anos","Estrutura de madeira: 1 ano"],destaques:["Estrutura de madeira de reflorestamento tratada","Lâmina de espuma firme certificada","Tecido antiderrapante","Sistema No Turn"]},
 "baby-pro-saude":{altura:"12 cm",medidas:["130 x 60","130 x 70"],garantia:["Espuma: 2 anos"],destaques:["Tecido com tratamento Actguard, que inibe ácaros, fungos e bactérias","Lâmina de espuma selada certificada pelo Inmetro"]},
 "fashion-superpocket":{altura:"23 cm",medidas:["88 x 188","138 x 188","158 x 198"],garantia:["Molas: 1 ano","Espuma: 1 ano"],destaques:["Mini-molas Superpocket ensacadas individualmente","Lâmina 100% EPS, que não retém calor","Reforço lateral em poliuretano","Sistema No Turn"]},
 "fashion-nanolastic":{altura:"23 cm",medidas:["88 x 188","138 x 188","158 x 198"],garantia:["Molas: 1 ano","Espuma: 1 ano"],destaques:["Mini-molas Nanolastic bicônicas","Lâmina 100% EPS, que não retém calor","Reforço lateral em poliuretano","Sistema No Turn"]},
 "fashion-firm":{altura:"14 cm",medidas:["88 x 188","138 x 188","158 x 198"],garantia:["Espuma: 1 ano"],destaques:["Lâmina de espuma firme certificada","Lâmina 100% EPS","Reforço lateral em poliuretano","Sistema No Turn"]},
 "fashion-confortavel":{altura:"14 cm",medidas:["88 x 188","108 x 198","138 x 188","158 x 198"],garantia:["Espuma: 6 meses"],destaques:["Tecido resistente em poliéster","Bordado em matelassê com espuma certificada"]},
 "fashion-standard":{altura:"14 cm",medidas:["88 x 188","138 x 188"],garantia:["Espuma: 6 meses"],destaques:["Tecido resistente em poliéster","Bordado em matelassê com espuma certificada"]},
 "colchonete-all-day":{altura:"8 cm",medidas:["88 x 188","138 x 188"],garantia:["Espuma: 90 dias"],destaques:["Tecido resistente em poliéster","Lâmina de espuma certificada"]}
};
