// ===================================================================
// BANCO DE PRODUTOS ORTOBOM T-7
// Cada produto: id, name, category, line (quando aplicável), image, desc, keywords (termos extras pra busca)
// Categorias vazias (bases, cabeceiras, roupas-de-cama, travesseiros,
// moveis) ainda não têm produtos reais cadastrados — telas "em breve".
// ===================================================================

// ===================================================================
// BANCO DE PRODUTOS ORTOBOM T-7
// Cada produto: id, name, category, line (quando aplicável), images (array — 1 ou mais fotos/cores/ângulos), desc.
// Categorias vazias (bases, cabeceiras, roupas-de-cama, travesseiros,
// moveis) ainda não têm produtos reais cadastrados — telas "em breve".
//
// COMO ADICIONAR FOTOS EXTRAS (cor/ângulo) A UM PRODUTO:
// troque `images:[{url:"arquivo.jpg", label:"Padrão"}]` por várias entradas, ex:
// images:[
//   {url:"orion-preto.jpg", label:"Preto"},
//   {url:"orion-cinza.jpg", label:"Cinza"},
// ]
// A primeira imagem do array é sempre a foto de capa (usada nos cards/busca).
// ===================================================================

const PRODUCTS = [
  // ---------- COLCHÕES · LINHA OURO ----------
  {id:"orion", name:"Orion", category:"colchoes", line:"Linha Ouro",
   desc:"Espuma HR de alta resiliência com tecido antiviral V-Protect.",
   images:[{url:"orion.jpg", label:"Padrão"}, {url:"orion-detail.jpg", label:"Detalhe"}, {url:"orion-g1.jpg", label:"Ambiente"}, {url:"orion-g2.jpg", label:"Ambiente"}, {url:"orion-g3.jpg", label:"Ambiente"}, {url:"orion-g4.jpg", label:"Ambiente"}, {url:"orion-g5.jpg", label:"Detalhe"}, {url:"orion-g6.jpg", label:"Detalhe"}, {url:"orion-g7.jpg", label:"Produto"}, {url:"orion-g8.jpg", label:"Produto"}]},
  {id:"bellona", name:"Bellona", category:"colchoes", line:"Linha Ouro",
   desc:"Malha Belga com Pillow Top viscoelástico. Nobreza e sofisticação.",
   images:[{url:"bellona.jpg", label:"Padrão"}, {url:"bellona-detail.jpg", label:"Detalhe"}, {url:"bellona-g1.jpg", label:"Ambiente"}, {url:"bellona-g2.jpg", label:"Ambiente"}, {url:"bellona-g3.jpg", label:"Produto"}, {url:"bellona-g4.jpg", label:"Produto"}, {url:"bellona-g5.jpg", label:"Detalhe"}, {url:"bellona-g6.jpg", label:"Detalhe"}]},
  {id:"orthopur", name:"Orthopur", category:"colchoes", line:"Linha Ouro",
   desc:"Tecnologia Fresh Touch — frescor imediato em qualquer noite.",
   images:[{url:"orthopur.jpg", label:"Padrão"}, {url:"orthopur-detail.jpg", label:"Detalhe"}, {url:"orthopur-g1.jpg", label:"Ambiente"}, {url:"orthopur-g2.jpg", label:"Ambiente"}, {url:"orthopur-g3.jpg", label:"Ambiente"}, {url:"orthopur-g4.jpg", label:"Ambiente"}, {url:"orthopur-g5.jpg", label:"Detalhe"}, {url:"orthopur-g6.jpg", label:"Detalhe"}, {url:"orthopur-g7.jpg", label:"Produto"}, {url:"orthopur-g8.jpg", label:"Detalhe"}]},
  {id:"liberty", name:"Liberty", category:"colchoes", line:"Linha Ouro",
   desc:"Fibra sustentável feita de garrafas PET recicladas.",
   images:[{url:"liberty.jpg", label:"Padrão"}, {url:"liberty-detail.jpg", label:"Detalhe"}, {url:"liberty-g1.jpg", label:"Ambiente"}, {url:"liberty-g2.jpg", label:"Ambiente"}, {url:"liberty-g3.jpg", label:"Ambiente"}, {url:"liberty-g4.jpg", label:"Ambiente"}, {url:"liberty-g5.jpg", label:"Detalhe"}, {url:"liberty-g6.jpg", label:"Detalhe"}, {url:"liberty-g7.jpg", label:"Produto"}, {url:"liberty-g8.jpg", label:"Produto"}]},
  {id:"pro-forca", name:"Pró Força", category:"colchoes", line:"Linha Ouro",
   desc:"Estrutura resistente com espuma sustentável certificada.",
   images:[{url:"pro-forca.jpg", label:"Padrão"}, {url:"pro-forca-detail.jpg", label:"Ambiente"}, {url:"pro-forca-g1.jpg", label:"Ambiente"}, {url:"pro-forca-g2.jpg", label:"Ambiente"}, {url:"pro-forca-g3.jpg", label:"Detalhe"}, {url:"pro-forca-g4.jpg", label:"Detalhe"}, {url:"pro-forca-g5.jpg", label:"Produto"}, {url:"pro-forca-g6.jpg", label:"Produto"}, {url:"pro-forca-g7.jpg", label:"Produto"}, {url:"pro-forca-g8.jpg", label:"Detalhe"}]},
  {id:"absolut-hybrid", name:"Absolut Hybrid", category:"colchoes", line:"Linha Ouro",
   desc:"Dupla face — um lado firme, outro macio. Você escolhe.",
   images:[{url:"absolut-hybrid.jpg", label:"Padrão"}, {url:"absolut-hybrid-detail.jpg", label:"Detalhe"}, {url:"absolut-hybrid-g1.jpg", label:"Ambiente"}, {url:"absolut-hybrid-g2.jpg", label:"Ambiente"}, {url:"absolut-hybrid-g3.jpg", label:"Detalhe"}, {url:"absolut-hybrid-g4.jpg", label:"Detalhe"}]},
  {id:"ouro-spring", name:"Ouro Spring", category:"colchoes", line:"Linha Ouro",
   desc:"Molas de fio contínuo com resistência progressiva.",
   images:[{url:"ouro-spring.jpg", label:"Padrão"}, {url:"ouro-spring-detail.jpg", label:"Ambiente"}, {url:"ouro-spring-g1.jpg", label:"Detalhe"}, {url:"ouro-spring-g2.jpg", label:"Detalhe"}, {url:"ouro-spring-g3.jpg", label:"Produto"}, {url:"ouro-spring-g4.jpg", label:"Produto"}, {url:"ouro-spring-g5.jpg", label:"Produto"}, {url:"ouro-spring-g6.jpg", label:"Produto"}, {url:"ouro-spring-g7.jpg", label:"Produto"}, {url:"ouro-spring-g8.jpg", label:"Produto"}]},
  {id:"light-ortopedico", name:"Light Ortopédico", category:"colchoes",
   desc:"Firmeza, resistência e suporte para quem busca um colchão ortopédico, com estrutura em madeira de reflorestamento sobre placa de EPS.",
   images:[{url:"light-ortopedico.jpg", label:"Padrão"}, {url:"light-ortopedico-g1.jpg", label:"Detalhe"}]},
  {id:"ortopedico-premium", name:"Ortopédico Premium", category:"colchoes", line:"Linha Ouro",
   desc:"Estrutura em madeira de reflorestamento, firmeza máxima.",
   images:[{url:"ortopedico-premium.jpg", label:"Padrão"}, {url:"ortopedico-premium-detail.jpg", label:"Outro ângulo"}, {url:"ortopedico-premium-g1.jpg", label:"Ambiente"}, {url:"ortopedico-premium-g2.jpg", label:"Ambiente"}, {url:"ortopedico-premium-g3.jpg", label:"Ambiente"}, {url:"ortopedico-premium-g4.jpg", label:"Detalhe"}, {url:"ortopedico-premium-g5.jpg", label:"Detalhe"}, {url:"ortopedico-premium-g6.jpg", label:"Detalhe"}, {url:"ortopedico-premium-g7.jpg", label:"Produto"}, {url:"ortopedico-premium-g8.jpg", label:"Produto"}]},

  // ---------- COLCHÕES · PRÓ SAÚDE ----------
  {id:"only", name:"Only", category:"colchoes", line:"Pró Saúde",
   desc:"Embalado a vácuo — cabe em elevador, sem precisar de caminhão.",
   images:[{url:"only.jpg", label:"Padrão"}, {url:"only-g1.jpg", label:"Ambiente"}, {url:"only-g2.jpg", label:"Ambiente"}, {url:"only-g3.jpg", label:"Ambiente"}, {url:"only-g4.jpg", label:"Produto"}, {url:"only-g5.jpg", label:"Detalhe"}, {url:"only-g6.jpg", label:"Detalhe"}, {url:"only-g7.jpg", label:"Produto"}, {url:"only-g8.jpg", label:"Camadas"}]},
  {id:"pro-saude-visco-adapt", name:"Pró Saúde Visco Adapt", category:"colchoes", line:"Pró Saúde",
   desc:"Camada viscoelástica que molda o formato do corpo.",
   images:[{url:"pro-saude-visco-adapt.jpg", label:"Padrão"}, {url:"pro-saude-visco-adapt-g1.jpg", label:"Produto"}, {url:"pro-saude-visco-adapt-g2.jpg", label:"Produto"}, {url:"pro-saude-visco-adapt-g3.jpg", label:"Produto"}, {url:"pro-saude-visco-adapt-g4.jpg", label:"Detalhe"}, {url:"pro-saude-visco-adapt-g5.jpg", label:"Detalhe"}, {url:"pro-saude-visco-adapt-g6.jpg", label:"Produto"}, {url:"pro-saude-visco-adapt-g7.jpg", label:"Produto"}, {url:"pro-saude-visco-adapt-g8.jpg", label:"Produto"}]},
  {id:"pro-saude-superpocket", name:"Pró Saúde Superpocket", category:"colchoes", line:"Pró Saúde",
   desc:"Molas ensacadas individualmente — conforto sem transferir movimento.",
   images:[{url:"pro-saude-superpocket.jpg", label:"Padrão"}, {url:"pro-saude-superpocket-detail.jpg", label:"Detalhe"}, {url:"pro-saude-superpocket-g1.jpg", label:"Ambiente"}, {url:"pro-saude-superpocket-g2.jpg", label:"Ambiente"}, {url:"pro-saude-superpocket-g3.jpg", label:"Ambiente"}, {url:"pro-saude-superpocket-g4.jpg", label:"Detalhe"}, {url:"pro-saude-superpocket-g5.jpg", label:"Ambiente"}, {url:"pro-saude-superpocket-g6.jpg", label:"Detalhe"}, {url:"pro-saude-superpocket-g7.jpg", label:"Ambiente"}, {url:"pro-saude-superpocket-g8.jpg", label:"Ambiente"}]},
  {id:"pro-saude-nanolastic", name:"Pró Saúde Nanolastic", category:"colchoes", line:"Pró Saúde",
   desc:"Molas bicônicas com resistência progressiva ao peso.",
   images:[{url:"pro-saude-nanolastic.jpg", label:"Padrão"}, {url:"pro-saude-nanolastic-detail.jpg", label:"Ambiente"}, {url:"pro-saude-nanolastic-g1.jpg", label:"Ambiente"}, {url:"pro-saude-nanolastic-g2.jpg", label:"Detalhe"}, {url:"pro-saude-nanolastic-g3.jpg", label:"Ambiente"}, {url:"pro-saude-nanolastic-g4.jpg", label:"Detalhe"}, {url:"pro-saude-nanolastic-g5.jpg", label:"Ambiente"}, {url:"pro-saude-nanolastic-g6.jpg", label:"Produto"}, {url:"pro-saude-nanolastic-g7.jpg", label:"Detalhe"}, {url:"pro-saude-nanolastic-g8.jpg", label:"Produto"}]},
  {id:"pro-saude-extra-firme", name:"Pró Saúde Extra Firme", category:"colchoes", line:"Pró Saúde",
   desc:"Sustentação extra pra quem prefere firmeza.",
   images:[{url:"pro-saude-extra-firme.jpg", label:"Padrão"}, {url:"pro-saude-extra-firme-g1.jpg", label:"Ambiente"}, {url:"pro-saude-extra-firme-g2.jpg", label:"Ambiente"}, {url:"pro-saude-extra-firme-g3.jpg", label:"Ambiente"}, {url:"pro-saude-extra-firme-g4.jpg", label:"Detalhe"}, {url:"pro-saude-extra-firme-g5.jpg", label:"Produto"}, {url:"pro-saude-extra-firme-g6.jpg", label:"Produto"}, {url:"pro-saude-extra-firme-g7.jpg", label:"Detalhe"}]},
  {id:"pro-saude-ortopedico", name:"Pró Saúde Ortopédico", category:"colchoes", line:"Pró Saúde",
   desc:"Estrutura em madeira tratada, ecologicamente correta.",
   images:[{url:"pro-saude-ortopedico.jpg", label:"Padrão"}, {url:"pro-saude-ortopedico-detail.jpg", label:"Detalhe"}, {url:"pro-saude-ortopedico-g1.jpg", label:"Ambiente"}, {url:"pro-saude-ortopedico-g2.jpg", label:"Ambiente"}, {url:"pro-saude-ortopedico-g3.jpg", label:"Ambiente"}, {url:"pro-saude-ortopedico-g4.jpg", label:"Detalhe"}, {url:"pro-saude-ortopedico-g5.jpg", label:"Ambiente"}, {url:"pro-saude-ortopedico-g6.jpg", label:"Ambiente"}, {url:"pro-saude-ortopedico-g7.jpg", label:"Ambiente"}, {url:"pro-saude-ortopedico-g8.jpg", label:"Ambiente"}]},
  {id:"baby-pro-saude", name:"Baby Pró Saúde", category:"colchoes", line:"Pró Saúde",
   desc:"Tratamento Actguard contra ácaros e bactérias — feito pro bebê.",
   images:[{url:"baby-pro-saude.jpg", label:"Padrão"}, {url:"baby-pro-saude-g1.jpg", label:"Produto"}, {url:"baby-pro-saude-g2.jpg", label:"Detalhe"}, {url:"baby-pro-saude-g3.jpg", label:"Detalhe"}]},

  // ---------- COLCHÕES · FASHION ----------
  {id:"fashion-superpocket", name:"Fashion Superpocket", category:"colchoes", line:"Fashion",
   desc:"Mini-molas ensacadas com lâmina 100% EPS.",
   images:[{url:"fashion-superpocket.jpg", label:"Padrão"}, {url:"fashion-superpocket-detail.jpg", label:"Ambiente"}, {url:"fashion-superpocket-g1.jpg", label:"Produto"}, {url:"fashion-superpocket-g2.jpg", label:"Produto"}, {url:"fashion-superpocket-g3.jpg", label:"Produto"}, {url:"fashion-superpocket-g4.jpg", label:"Detalhe"}, {url:"fashion-superpocket-g5.jpg", label:"Detalhe"}, {url:"fashion-superpocket-g6.jpg", label:"Produto"}, {url:"fashion-superpocket-g7.jpg", label:"Produto"}, {url:"fashion-superpocket-g8.jpg", label:"Produto"}]},
  {id:"fashion-nanolastic", name:"Fashion Nanolastic", category:"colchoes", line:"Fashion",
   desc:"Molas bicônicas resistentes, ótimo custo-benefício.",
   images:[{url:"fashion-nanolastic.jpg", label:"Padrão"}, {url:"fashion-nanolastic-detail.jpg", label:"Ambiente"}, {url:"fashion-nanolastic-g1.jpg", label:"Produto"}, {url:"fashion-nanolastic-g2.jpg", label:"Produto"}, {url:"fashion-nanolastic-g3.jpg", label:"Produto"}, {url:"fashion-nanolastic-g4.jpg", label:"Detalhe"}, {url:"fashion-nanolastic-g5.jpg", label:"Detalhe"}, {url:"fashion-nanolastic-g6.jpg", label:"Produto"}, {url:"fashion-nanolastic-g7.jpg", label:"Produto"}, {url:"fashion-nanolastic-g8.jpg", label:"Produto"}]},
  {id:"fashion-firm", name:"Fashion Firm", category:"colchoes", line:"Fashion",
   desc:"Firmeza equilibrada com reforço lateral em PU.",
   images:[{url:"fashion-firm.jpg", label:"Padrão"}, {url:"fashion-firm-detail.jpg", label:"Ambiente"}, {url:"fashion-firm-g1.jpg", label:"Produto"}, {url:"fashion-firm-g2.jpg", label:"Produto"}, {url:"fashion-firm-g3.jpg", label:"Produto"}, {url:"fashion-firm-g4.jpg", label:"Detalhe"}, {url:"fashion-firm-g5.jpg", label:"Produto"}, {url:"fashion-firm-g6.jpg", label:"Produto"}, {url:"fashion-firm-g7.jpg", label:"Produto"}]},
  {id:"fashion-confortavel", name:"Fashion Confortável", category:"colchoes", line:"Fashion",
   desc:"Conforto acessível pra quem está montando a casa.",
   images:[{url:"fashion-confortavel.jpg", label:"Padrão"}, {url:"fashion-confortavel-g1.jpg", label:"Produto"}, {url:"fashion-confortavel-g2.jpg", label:"Produto"}, {url:"fashion-confortavel-g3.jpg", label:"Produto"}, {url:"fashion-confortavel-g4.jpg", label:"Detalhe"}, {url:"fashion-confortavel-g5.jpg", label:"Detalhe"}, {url:"fashion-confortavel-g6.jpg", label:"Produto"}, {url:"fashion-confortavel-g7.jpg", label:"Produto"}, {url:"fashion-confortavel-g8.jpg", label:"Produto"}]},
  {id:"fashion-standard", name:"Fashion Standard", category:"colchoes", line:"Fashion",
   desc:"Entrada Ortobom com a qualidade que a marca garante.",
   images:[{url:"fashion-standard.jpg", label:"Padrão"}, {url:"fashion-standard-g1.jpg", label:"Produto"}, {url:"fashion-standard-g2.jpg", label:"Produto"}, {url:"fashion-standard-g3.jpg", label:"Produto"}, {url:"fashion-standard-g4.jpg", label:"Detalhe"}, {url:"fashion-standard-g5.jpg", label:"Produto"}, {url:"fashion-standard-g6.jpg", label:"Produto"}, {url:"fashion-standard-g7.jpg", label:"Produto"}]},
  {id:"pillow-top-hr-gel", name:"Pillow Top HR Gel", category:"acessorios", line:"Pillow Top",
   desc:"Lâmina de espuma de alta resiliência gel, de 5 cm, que oferece suporte firme e resiliente.",
   images:[{url:"pillow-top-hr-gel.jpg", label:"Padrão"}, {url:"pillow-top-hr-gel-g1.jpg", label:"Aplicação"}, {url:"pillow-top-hr-gel-g2.jpg", label:"Detalhe"}, {url:"pillow-top-hr-gel-g3.jpg", label:"Toque"}, {url:"pillow-top-hr-gel-g4.jpg", label:"Aplicação"}]},
  {id:"colchonete-all-day-acessorio", name:"Colchonete All Day", category:"acessorios", line:"Uso Avulso",
   desc:"Solução prática pra visita, viagem ou quarto extra.",
   images:[{url:"colchonete-all-day.jpg", label:"Padrão"}, {url:"colchonete-all-day-acessorio-g1.jpg", label:"Produto"}, {url:"colchonete-all-day-acessorio-g2.jpg", label:"Produto"}, {url:"colchonete-all-day-acessorio-g3.jpg", label:"Produto"}]},
  {id:"almofada-rolete-nobuck", name:"Almofada Rolete Nobuck", category:"acessorios", line:"Uso Avulso",
   desc:"Almofada rolete em tecido nobuck extramatelado, com toque aveludado e enchimento em fibra siliconada 100% poliéster.",
   images:[{url:"almofada-rolete-camurca-brown.jpg", label:"Padrão"}, {url:"almofada-rolete-camurca-g1.jpg", label:"Detalhe"}]},
  {id:"encosto-dino-veludo", name:"Encosto Dino Veludo", category:"acessorios", line:"Uso Avulso",
   desc:"Encosto em veludo com suporte ergonômico, ideal para ler ou assistir TV.",
   images:[{url:"encosto-dino-veludo.jpg", label:"Padrão"}]},
  {id:"massageador-alveolado", name:"Massageador Alveolado", category:"acessorios", line:"Uso Avulso",
   desc:"Placa de espuma alveolada para usar sobre o colchão ou base plana, com tratamento antiácaro e antifungo.",
   images:[{url:"massageador-alveolado.jpg", label:"Padrão"}]},
  {id:"tapete-de-yoga", name:"Tapete de Yoga", category:"acessorios", line:"Uso Avulso",
   desc:"Tapete Ortobom para yoga e exercícios em casa.",
   images:[{url:"tapete-de-yoga.jpg", label:"Padrão"}, {url:"tapete-de-yoga-g1.jpg", label:"Produto"}]},

  {id:"encosto-ergonomico", name:"Encosto Ergonômico", category:"acessorios", line:"Suavencosto",
   desc:"Espuma viscoelástica com recortes anatômicos, suporte elástico e fivela regulável. Serve em cadeiras de escritório e no carro.",
   images:[{url:"encosto-ergonomico.jpg", label:"Padrão"}, {url:"encosto-ergonomico-g1.jpg", label:"Detalhe"}, {url:"encosto-ergonomico-g2.jpg", label:"Detalhe"}, {url:"encosto-ergonomico-g3.jpg", label:"Embalagem"}]},
  {id:"suavencosto-alveolado", name:"Suavencosto Alveolado", category:"acessorios", line:"Suavencosto",
   desc:"Suavencosto em espuma alveolada com capa atoalhada, para ler ou descansar na cama.",
   images:[{url:"suavencosto-alveolado.jpg", label:"Padrão"}, {url:"suavencosto-alveolado-g1.jpg", label:"Produto"}, {url:"suavencosto-alveolado-g2.jpg", label:"Detalhe"}]},
  {id:"suavencosto-infantil", name:"Suavencosto Infantil", category:"acessorios", line:"Suavencosto",
   desc:"Superfície macia e inclinada, pensada para o conforto do bebê, como no descanso após a amamentação.",
   images:[{url:"suavencosto-infantil.jpg", label:"Padrão"}, {url:"suavencosto-infantil-g1.jpg", label:"Produto"}]},
  {id:"colchonete-small-academia", name:"Colchonete Small para Academia", category:"acessorios", line:"Uso Avulso",
   desc:"Colchonete para academia com revestimento resistente e espuma ultra firme selada 100% poliuretano.",
   images:[{url:"colchonete-small-academia.jpg", label:"Padrão"}]},
  {id:"colchonete-big-academia", name:"Colchonete Big para Academia", category:"acessorios", line:"Uso Avulso",
   desc:"Colchonete de espuma com revestimento em PVC, para academia, ginástica e alongamento.",
   images:[{url:"colchonete-big-academia.jpg", label:"Padrão"}]},

  // ---------- BASES ----------
  {id:"base-sommier-bau-fashion-cori", name:"Base Sommier Baú Fashion Cori", category:"bases",
   desc:"Base baú com amplo espaço interno para guardar roupas de cama, toalhas e outros objetos. Revestimento Cori.",
   images:[{url:"base-sommier-bau-fashion-cori-black.jpg", label:"Preto"}, {url:"base-sommier-bau-fashion-cori-gray.jpg", label:"Cinza"}, {url:"base-sommier-bau-fashion-cori-g1.jpg", label:"Detalhe"}, {url:"base-sommier-bau-fashion-cori-g2.jpg", label:"Detalhe"}]},
  {id:"base-sommier-pro-forca", name:"Base Sommier Pró Força", category:"bases",
   desc:"Feita com madeira tratada de reflorestamento, para durabilidade e resistência.",
   images:[{url:"base-sommier-pro-forca.jpg", label:"Padrão"}, {url:"base-sommier-pro-forca-g1.jpg", label:"Detalhe"}, {url:"base-sommier-pro-forca-g2.jpg", label:"Detalhe"}, {url:"base-sommier-pro-forca-g3.jpg", label:"Detalhe"}, {url:"base-sommier-pro-forca-g4.jpg", label:"Detalhe"}, {url:"base-sommier-pro-forca-g5.jpg", label:"Detalhe"}, {url:"base-sommier-pro-forca-g6.jpg", label:"Detalhe"}]},
  {id:"base-sommier-liberty", name:"Base Sommier Liberty", category:"bases",
   desc:"Base plana com revestimento em tecido de malha 100% poliéster e estrutura de madeira de reflorestamento.",
   images:[{url:"base-sommier-liberty.jpg", label:"Padrão"}, {url:"base-sommier-liberty-g1.jpg", label:"Detalhe"}, {url:"base-sommier-liberty-g2.jpg", label:"Detalhe"}, {url:"base-sommier-liberty-g3.jpg", label:"Detalhe"}, {url:"base-sommier-liberty-g4.jpg", label:"Detalhe"}, {url:"base-sommier-liberty-g5.jpg", label:"Detalhe"}]},
  {id:"base-sommier-bellona", name:"Base Sommier Bellona", category:"bases",
   desc:"Base plana em madeira de reflorestamento, com revestimento lateral em tecido 100% poliéster com toque de linho.",
   images:[{url:"base-sommier-bellona.jpg", label:"Padrão"}, {url:"base-sommier-bellona-g1.jpg", label:"Detalhe"}, {url:"base-sommier-bellona-g2.jpg", label:"Detalhe"}, {url:"base-sommier-bellona-g3.jpg", label:"Detalhe"}, {url:"base-sommier-bellona-g4.jpg", label:"Detalhe"}, {url:"base-sommier-bellona-g5.jpg", label:"Detalhe"}]},
  {id:"base-sommier-bau-fashion-nobuck", name:"Base Sommier Baú Fashion Nobuck", category:"bases",
   desc:"Base baú com amplo espaço interno para guardar roupas de cama, toalhas e outros objetos. Revestimento nobuck.",
   images:[{url:"base-sommier-bau-fashion-nobuck-brown.jpg", label:"Marrom"}, {url:"base-sommier-bau-fashion-nobuck-gray.jpg", label:"Cinza"}, {url:"base-sommier-bau-fashion-nobuck-black.jpg", label:"Preto"}, {url:"base-sommier-bau-fashion-nobuck-cream.jpg", label:"Creme"}, {url:"base-sommier-bau-fashion-nobuck-g1.jpg", label:"Detalhe"}, {url:"base-sommier-bau-fashion-nobuck-g2.jpg", label:"Detalhe"}, {url:"base-sommier-bau-fashion-nobuck-g3.jpg", label:"Detalhe"}, {url:"base-sommier-bau-fashion-nobuck-g4.jpg", label:"Detalhe"}, {url:"base-sommier-bau-fashion-nobuck-g5.jpg", label:"Detalhe"}]},
  {id:"base-sommier-orthopur", name:"Base Sommier Orthopur", category:"bases",
   desc:"Base plana com revestimento em tecido de malha 100% poliéster e estrutura de madeira de reflorestamento.",
   images:[{url:"base-sommier-orthopur.jpg", label:"Padrão"}, {url:"base-sommier-orthopur-g1.jpg", label:"Detalhe"}, {url:"base-sommier-orthopur-g2.jpg", label:"Detalhe"}, {url:"base-sommier-orthopur-g3.jpg", label:"Detalhe"}, {url:"base-sommier-orthopur-g4.jpg", label:"Detalhe"}, {url:"base-sommier-orthopur-g5.jpg", label:"Detalhe"}]},
  {id:"base-sommier-bau-bi-cori", name:"Base Sommier Baú Cori", category:"bases",
   desc:"Base sommier estilo baú, com amplo espaço interno para guardar roupas de cama, toalhas e outros objetos, revestimento em Cori.",
   images:[{url:"base-sommier-bau-bi-cori-black.jpg", label:"Preto"}, {url:"base-sommier-bau-bi-cori-gray.jpg", label:"Cinza"}, {url:"base-sommier-bau-bi-cori-white.jpg", label:"Branco"}, {url:"base-sommier-bau-bi-cori-brown.jpg", label:"Marrom"}, {url:"base-sommier-bau-bi-cori-g1.jpg", label:"Detalhe"}, {url:"base-sommier-bau-bi-cori-g2.jpg", label:"Detalhe"}, {url:"base-sommier-bau-bi-cori-g3.jpg", label:"Detalhe"}, {url:"base-sommier-bau-bi-cori-g4.jpg", label:"Detalhe"}, {url:"base-sommier-bau-bi-cori-g5.jpg", label:"Detalhe"}, {url:"base-sommier-bau-bi-cori-g6.jpg", label:"Detalhe"}]},
  {id:"base-sommier-bau-bi-nobuck", name:"Base Sommier Baú Nobuck", category:"bases",
   desc:"Base sommier estilo baú, com amplo espaço interno para guardar roupas de cama, toalhas e outros objetos, revestimento em nobuck.",
   images:[{url:"base-sommier-bau-bi-nobuck-gray.jpg", label:"Cinza"}, {url:"base-sommier-bau-bi-nobuck-black.jpg", label:"Preto"}, {url:"base-sommier-bau-bi-nobuck-g1.jpg", label:"Detalhe"}, {url:"base-sommier-bau-bi-nobuck-g2.jpg", label:"Detalhe"}, {url:"base-sommier-bau-bi-nobuck-g3.jpg", label:"Detalhe"}, {url:"base-sommier-bau-bi-nobuck-g4.jpg", label:"Detalhe"}]},
  {id:"base-sommier-cori", name:"Base Sommier Cori", category:"bases",
   desc:"Base com acabamento Cori, disponível em várias cores.",
   images:[{url:"base-sommier-cori-white.jpg", label:"Branco"}, {url:"base-sommier-cori-black.jpg", label:"Preto"}, {url:"base-sommier-cori-g1.jpg", label:"Detalhe"}, {url:"base-sommier-cori-g2.jpg", label:"Detalhe"}, {url:"base-sommier-cori-g3.jpg", label:"Detalhe"}, {url:"base-sommier-cori-g4.jpg", label:"Detalhe"}, {url:"base-sommier-cori-g5.jpg", label:"Detalhe"}]},
  {id:"base-sommier-orion", name:"Base Sommier Orion", category:"bases",
   desc:"Base plana com revestimento em tecido de malha 100% poliéster e estrutura de madeira tratada, de reflorestamento.",
   images:[{url:"base-sommier-orion.jpg", label:"Padrão"}, {url:"base-sommier-orion-g1.jpg", label:"Detalhe"}, {url:"base-sommier-orion-g2.jpg", label:"Detalhe"}]},
  {id:"base-sommier-absolut", name:"Base Sommier Absolut", category:"bases",
   desc:"Base plana com revestimento em tecido de malha 100% poliéster, pensada para o conforto e o suporte do seu colchão.",
   images:[{url:"base-sommier-absolut.jpg", label:"Padrão"}, {url:"base-sommier-absolut-g1.jpg", label:"Detalhe"}, {url:"base-sommier-absolut-g2.jpg", label:"Detalhe"}]},
  {id:"base-sommier-pro-saude", name:"Base Sommier Pró Saúde", category:"bases",
   desc:"Base plana com estrutura em madeira de reflorestamento e revestimento em tecido plano 100% poliéster.",
   images:[{url:"base-sommier-pro-saude.jpg", label:"Marrom"}, {url:"base-sommier-pro-saude-g1.jpg", label:"Detalhe"}, {url:"base-sommier-pro-saude-g2.jpg", label:"Padrão"}, {url:"base-sommier-pro-saude-g3.jpg", label:"Ambiente"}]},
  {id:"base-sommier-bau-linho", name:"Base Sommier Baú Linho", category:"bases",
   desc:"Base baú com revestimento em linho e amplo espaço interno para guardar roupas de cama, toalhas e outros objetos.",
   images:[{url:"base-sommier-bau-linho-gray.jpg", label:"Cinza"}, {url:"base-sommier-bau-linho-g1.jpg", label:"Detalhe"}, {url:"base-sommier-bau-linho-g2.jpg", label:"Detalhe"}, {url:"base-sommier-bau-linho-g3.jpg", label:"Detalhe"}, {url:"base-sommier-bau-linho-g4.jpg", label:"Aberta"}, {url:"base-sommier-bau-linho-g5.jpg", label:"Uso"}]},
  // ---------- CABECEIRAS ----------
  {id:"cabeceira-cherie", name:"Cabeceira Cherie Linho", category:"cabeceiras",
   desc:"Design geométrico em blocos, com revestimento em linho e cinco tamanhos.",
   images:[{url:"cabeceira-cherie-g1.jpg", label:"Preto"}, {url:"cabeceira-cherie-g2.jpg", label:"Preto · frente"}, {url:"cabeceira-cherie-g3.jpg", label:"Preto · outro tamanho"}]},
  {id:"cabeceira-cherie-veludo", name:"Cabeceira Cherie Veludo", category:"cabeceiras",
   desc:"Design geométrico em blocos, com revestimento em veludo e cinco tamanhos.",
   images:[{url:"cabeceira-cherie-veludo-g1.jpg", label:"Cinza"}, {url:"cabeceira-cherie-veludo-g2.jpg", label:"Cinza · frente"}, {url:"cabeceira-cherie-veludo-g3.jpg", label:"Cinza · outro tamanho"}, {url:"cabeceira-cherie-veludo-g4.jpg", label:"Cinza · outro tamanho"}]},
  {id:"cabeceira-glamour", name:"Cabeceira Glamour Linho", category:"cabeceiras",
   desc:"Painéis verticais estofados, com revestimento em linho e cinco tamanhos.",
   images:[{url:"cabeceira-glamour-g1.jpg", label:"Cinza"}, {url:"cabeceira-glamour-g2.jpg", label:"Cinza · frente"}, {url:"cabeceira-glamour-g3.jpg", label:"Detalhe do tecido"}, {url:"cabeceira-glamour-g4.jpg", label:"Preto"}, {url:"cabeceira-glamour-g5.jpg", label:"Marrom"}, {url:"cabeceira-glamour-g6.jpg", label:"Bege"}]},
  {id:"cabeceira-lieve-cori", name:"Cabeceira Lieve Cori", category:"cabeceiras",
   desc:"Design minimalista de linhas simples, com revestimento em corino.",
   images:[{url:"cabeceira-lieve-cori-g1.jpg", label:"Preto"}, {url:"cabeceira-lieve-cori-g2.jpg", label:"Preto · frente"}, {url:"cabeceira-lieve-cori-g3.jpg", label:"Preto · outro tamanho"}, {url:"cabeceira-lieve-cori-g4.jpg", label:"Marrom"}, {url:"cabeceira-lieve-cori-g5.jpg", label:"Marrom"}]},
  {id:"cabeceira-lovely-facto", name:"Cabeceira Lovely Facto", category:"cabeceiras",
   desc:"Inspirada nos modelos Chesterfield, com detalhes em botões e linhas suaves.",
   images:[{url:"cabeceira-lovely-facto-g1.jpg", label:"Creme"}, {url:"cabeceira-lovely-facto-g2.jpg", label:"Creme · frente"}, {url:"cabeceira-lovely-facto-g3.jpg", label:"Detalhe"}, {url:"cabeceira-lovely-facto-g4.jpg", label:"Branco"}, {url:"cabeceira-lovely-facto-g5.jpg", label:"Branco · outro tamanho"}]},

  // ---------- MÓVEIS ----------
  {id:"sofa-cama-2l-veludo-azul-marinho", name:"Sofá Cama 2L Veludo Azul Marinho", category:"moveis",
   desc:"Sofá-cama multifuncional, com base que se transforma em cama de casal. Ideal para receber família e visitas.",
   images:[{url:"sofa-cama-2l-veludo-azul-marinho.jpg", label:"Padrão"}, {url:"sofa-cama-2l-veludo-azul-marinho-g1.jpg", label:"Frontal"}, {url:"sofa-cama-2l-veludo-azul-marinho-g2.jpg", label:"Aberto"}, {url:"sofa-cama-2l-veludo-azul-marinho-g3.jpg", label:"Aberto"}, {url:"sofa-cama-2l-veludo-azul-marinho-g4.jpg", label:"Lateral"}, {url:"sofa-cama-2l-veludo-azul-marinho-g5.jpg", label:"Medidas"}]},
  {id:"sofa-cama-2l-linho-cinza", name:"Sofá Cama 2L Linho Cinza", category:"moveis",
   desc:"Sofá-cama multifuncional, com base que se transforma em cama de casal. Ideal para receber família e visitas.",
   images:[{url:"sofa-cama-2l-linho-cinza.jpg", label:"Padrão"}, {url:"sofa-cama-2l-linho-cinza-g1.jpg", label:"Ambiente"}, {url:"sofa-cama-2l-linho-cinza-g2.jpg", label:"Aberto"}, {url:"sofa-cama-2l-linho-cinza-g3.jpg", label:"Lateral"}, {url:"sofa-cama-2l-linho-cinza-g4.jpg", label:"Fechado"}, {url:"sofa-cama-2l-linho-cinza-g5.jpg", label:"Medidas"}]},
  {id:"sofa-cama-malu", name:"Sofá Cama 3L Linho Bege", category:"moveis",
   desc:"Sofá-cama multifuncional, com base que se transforma em cama de casal. Ideal para receber família e visitas.",
   images:[{url:"sofa-cama-malu.jpg", label:"Padrão"}, {url:"sofa-cama-malu-g1.jpg", label:"Produto"}, {url:"sofa-cama-malu-g2.jpg", label:"Produto"}]},
  {id:"sofa-cama-3l-veludo-azul-marinho", name:"Sofá Cama 3L Veludo Azul Marinho", category:"moveis",
   desc:"Sofá-cama multifuncional, com base que se transforma em cama de casal. Ideal para receber família e visitas.",
   images:[{url:"sofa-cama-3l-veludo-azul-marinho.jpg", label:"Padrão"}, {url:"sofa-cama-3l-veludo-azul-marinho-g1.jpg", label:"Produto"}, {url:"sofa-cama-3l-veludo-azul-marinho-g2.jpg", label:"Aberto"}, {url:"sofa-cama-3l-veludo-azul-marinho-g3.jpg", label:"Medidas"}]},
  {id:"poltrona-reclinavel-cori", name:"Poltrona Reclinável Ortobom Cori", category:"moveis",
   desc:"Poltrona reclinável de 1 lugar, com articulação metálica Zerowall de abertura suave.",
   images:[{url:"poltrona-reclinavel-cori.jpg", label:"Padrão"}, {url:"poltrona-reclinavel-cori-g1.jpg", label:"Ambiente"}, {url:"poltrona-reclinavel-cori-g2.jpg", label:"Produto"}]},
  {id:"poltrona-reclinavel-nobuck", name:"Poltrona Reclinável Ortobom Nobuck", category:"moveis",
   desc:"Poltrona reclinável de 1 lugar, com revestimento em nobuck e articulação de abertura suave.",
   images:[{url:"poltrona-reclinavel-nobuck.jpg", label:"Padrão"}, {url:"poltrona-reclinavel-nobuck-g1.jpg", label:"Reclinada"}, {url:"poltrona-reclinavel-nobuck-g2.jpg", label:"Produto"}]},
  {id:"poltrona-reclinavel-premium-nobuck", name:"Poltrona Reclinável Ortobom Premium Nobuck", category:"moveis",
   desc:"Poltrona reclinável de 1 lugar, com articulação Zerowall e revestimento em nobuck.",
   images:[{url:"poltrona-reclinavel-premium-nobuck.jpg", label:"Padrão"}, {url:"poltrona-reclinavel-premium-nobuck-g1.jpg", label:"Reclinada"}, {url:"poltrona-reclinavel-premium-nobuck-g2.jpg", label:"Medidas"}]},
  {id:"poltrona-massageadora-relax", name:"Poltrona Massageadora Ortobom Cori", category:"moveis",
   desc:"Poltrona reclinável com massagem, com comandos acessíveis pelo controle remoto.",
   images:[{url:"poltrona-massageadora-relax-g1.jpg", label:"Produto"}, {url:"poltrona-massageadora-relax-g2.jpg", label:"Produto"}, {url:"poltrona-massageadora-relax-g3.jpg", label:"Produto"}, {url:"poltrona-massageadora-relax-g4.jpg", label:"Medidas"}, {url:"poltrona-massageadora-relax-g5.jpg", label:"Recursos"}, {url:"poltrona-massageadora-relax-g6.jpg", label:"Inclinação"}, {url:"poltrona-massageadora-relax.jpg", label:"Padrão"}]},

  // ---------- TRAVESSEIROS ----------
  {id:"travesseiro-anatomic-visco", name:"Travesseiro Anatomic Visco", category:"travesseiros",
   desc:"Travesseiro de espuma viscoelástica, firme, com capa em malha.",
   images:[{url:"travesseiro-anatomic-visco.jpg", label:"Padrão"}, {url:"travesseiro-anatomic-visco-g1.jpg", label:"Produto"}, {url:"travesseiro-anatomic-visco-g2.jpg", label:"Produto"}]},
  {id:"travesseiro-corpo-hug", name:"Travesseiro de Corpo Hug", category:"travesseiros",
   desc:"Travesseiro de corpo, longo, com enchimento em fibra siliconada.",
   images:[{url:"travesseiro-corpo-hug.jpg", label:"Padrão"}, {url:"travesseiro-corpo-hug-g1.jpg", label:"Ambiente"}]},
  {id:"travesseiro-pluma-ganso", name:"Travesseiro Pluma de Ganso", category:"travesseiros",
   desc:"Travesseiro macio com enchimento 100% plumas de ganso.",
   images:[{url:"travesseiro-pluma-ganso.jpg", label:"Padrão"}]},
  {id:"travesseiro-pro-latex-gel", name:"Travesseiro Pró Látex Gel", category:"travesseiros",
   desc:"Espuma de alta resiliência com manta de gel, de apoio firme.",
   images:[{url:"travesseiro-pro-latex-gel.jpg", label:"Padrão"}]},
  {id:"travesseiro-sonho", name:"Travesseiro Sonho", category:"travesseiros",
   desc:"Travesseiro firme de espuma hiper soft, com revestimento em poliéster.",
   images:[{url:"travesseiro-sonho.jpg", label:"Padrão"}, {url:"travesseiro-sonho-g1.jpg", label:"Ambiente"}, {url:"travesseiro-sonho-g2.jpg", label:"Ambiente"}]},
  {id:"travesseiro-royal-pillow", name:"Travesseiro Royal Pillow", category:"travesseiros",
   desc:"Travesseiro macio de fibra siliconada, com revestimento em algodão.",
   images:[{url:"travesseiro-royal-pillow.jpg", label:"Padrão"}, {url:"travesseiro-royal-pillow-g1.jpg", label:"Ambiente"}]},
  {id:"travesseiro-viscopur", name:"Travesseiro Viscopur", category:"travesseiros",
   desc:"Travesseiro firme de espuma viscoelástica, com revestimento em algodão.",
   images:[{url:"travesseiro-viscopur.jpg", label:"Padrão"}, {url:"travesseiro-viscopur-g1.jpg", label:"Ambiente"}]},
  {id:"travesseiro-pro-latex", name:"Travesseiro Pró Látex", category:"travesseiros",
   desc:"Espuma de alta resiliência que une maciez, suporte e frescor.",
   images:[{url:"travesseiro-pro-latex.jpg", label:"Padrão"}, {url:"travesseiro-pro-latex-g1.jpg", label:"Ambiente"}]},
  {id:"travesseiro-viscopur-gel", name:"Travesseiro Viscopur Gel", category:"travesseiros",
   desc:"Espuma viscoelástica com manta de gel refrescante, que ajuda a manter uma temperatura agradável.",
   images:[{url:"travesseiro-viscopur-gel.jpg", label:"Padrão"}, {url:"travesseiro-viscopur-gel-g1.jpg", label:"Detalhe"}, {url:"travesseiro-viscopur-gel-g2.jpg", label:"Detalhe"}]},
  {id:"travesseiro-conforto-regulavel", name:"Travesseiro Conforto Regulável", category:"travesseiros",
   desc:"Pode ser ajustado em duas alturas diferentes, para se adaptar ao seu jeito de dormir.",
   images:[{url:"travesseiro-conforto-regulavel.jpg", label:"Padrão"}]},
  {id:"travesseiro-seis-estrelas", name:"Travesseiro Seis Estrelas", category:"travesseiros",
   desc:"Travesseiro macio de fibra siliconada, ideal para quem prefere um suporte mais baixo.",
   images:[{url:"travesseiro-seis-estrelas.jpg", label:"Padrão"}]},
  {id:"travesseiro-seis-estrelas-enrolado", name:"Travesseiro Seis Estrelas Enrolado", category:"travesseiros",
   desc:"Travesseiro macio de fibra siliconada, ideal para quem prefere um suporte mais baixo.",
   images:[{url:"travesseiro-seis-estrelas-enrolado.jpg", label:"Padrão"}]},
  {id:"travesseiro-flock", name:"Travesseiro Flock", category:"travesseiros",
   desc:"Espuma viscoelástica flocada, firme, com revestimento em malha de poliéster.",
   images:[{url:"travesseiro-flock.jpg", label:"Padrão"}, {url:"travesseiro-flock-g1.jpg", label:"Ambiente"}]},
  {id:"capa-protetora-travesseiro", name:"Capa Protetora para Travesseiro Impermeável", category:"roupas-de-cama",
   desc:"Capa impermeável que protege o travesseiro contra líquidos e ácaros.",
   images:[{url:"capa-protetora-travesseiro.jpg", label:"Padrão"}, {url:"capa-protetora-travesseiro-g1.jpg", label:"Detalhe"}]},
  {id:"protetor-colchao-fresh-touch", name:"Protetor de Colchão Fresh Touch", category:"roupas-de-cama",
   desc:"Protetor de colchão com tecnologia Fresh Touch, que traz sensação de frescor.",
   images:[{url:"protetor-colchao-fresh-touch.jpg", label:"Padrão"}, {url:"protetor-colchao-fresh-touch-g1.jpg", label:"Tecido"}]},
  {id:"protetor-colchao-infantil", name:"Protetor de Colchão Infantil Impermeável", category:"roupas-de-cama",
   desc:"Protetor impermeável indicado para colchões infantis.",
   images:[{url:"protetor-colchao-infantil.jpg", label:"Padrão"}, {url:"protetor-colchao-infantil-g1.jpg", label:"Ambiente"}]},
];

// Categorias do menu, na ordem de exibição, com metadados de cada página
const CATEGORIES = [
  {id:"colchoes", label:"Colchões", page:"colchoes.html"},
  {id:"bases", label:"Bases", page:"bases.html"},
  {id:"cabeceiras", label:"Cabeceiras", page:"cabeceiras.html"},
  {id:"roupas-de-cama", label:"Roupas de Cama", page:"roupas-de-cama.html"},
  {id:"travesseiros", label:"Travesseiros", page:"travesseiros.html"},
  {id:"acessorios", label:"Acessórios", page:"acessorios.html"},
  {id:"moveis", label:"Móveis", page:"moveis.html"},
];

function getProductsByCategory(cat){
  return PRODUCTS.filter(p => p.category === cat);
}

// Primeira imagem do array = foto de capa (usada em cards, busca, relacionados)
function coverImage(p){
  return (p.images && p.images[0]) ? p.images[0].url : 'placeholder.jpg';
}
